#ifndef _CHESSENUMS_H
#define _CHESSENUMS_H

typedef enum {
    CHESS_OUT_OF_MEMORY,
    CHESS_NULL_ARGUMENT,
    CHESS_INVALID_ID,
    CHESS_INVALID_LOCATION,
    CHESS_INVALID_MAX_GAMES,
    CHESS_TOURNAMENT_ALREADY_EXISTS,
    CHESS_TOURNAMENT_NOT_EXIST,
    CHESS_GAME_ALREADY_EXISTS,
    CHESS_INVALID_PLAY_TIME,
    CHESS_EXCEEDED_GAMES,
    CHESS_PLAYER_NOT_EXIST,
    CHESS_TOURNAMENT_ENDED,
    CHESS_NO_TOURNAMENTS_ENDED,
    CHESS_SAVE_FAILURE,
    CHESS_SUCCESS
} ChessResult ;

typedef enum {
    FIRST_PLAYER,
    SECOND_PLAYER,
    DRAW
} Winner;

#endif //_CHESSENUMS_H
